before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz
  - tar -xzf apache-cassandra-2.2.4-bin.tar.gz
  - sudo sh apache-cassandra-2.2.4/bin/cassandra > /dev/null
cache:
  directories:
    - $HOME/.cache/rebar3
language: erlang
notifications:
  email: false
otp_release:
  - 18.0
  - 17.5
script: "make test"
sudo: required
