before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz
  - tar -xzf apache-cassandra-2.2.4-bin.tar.gz
  - sudo sh apache-cassandra-2.2.4/bin/cassandra > /dev/null
  - for i in {1..10}; do cqlsh -e "DESCRIBE keyspaces;" && break || sleep 2; done
cache:
  directories:
    - $HOME/.cache/rebar3
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 18.0
  - 17.5
script: "make travis"
sudo: required
